"""fix foreign keys for context_windows and user_patterns

Revision ID: 3eb5b3f4e931
Revises: 8f7c698118be
Create Date: 2026-01-10 17:03:47.601451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb5b3f4e931'
down_revision: Union[str, None] = '8f7c698118be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'context_windows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_patterns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_patterns', type_='foreignkey')
    op.drop_constraint(None, 'context_windows', type_='foreignkey')
    # ### end Alembic commands ###
